// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import type { CreateFavoriteData, CreateFavoriteResponses, CreateProjectData, CreateProjectResponses, CreateSectionData, CreateSectionResponses, CreateSubtaskData, CreateSubtaskResponses, CreateTaskData, CreateTaskResponses, CreateUserData, CreateUserResponses, CreateWorkspaceData, CreateWorkspaceResponses, DeleteFavoriteData, DeleteFavoriteResponses, DeleteProjectData, DeleteProjectResponses, DeleteSectionData, DeleteSectionResponses, DeleteSubtaskData, DeleteSubtaskResponses, DeleteTaskAttachmentData, DeleteTaskAttachmentResponses, DeleteTaskData, DeleteTaskResponses, DeleteUserData, DeleteUserResponses, DeleteWorkspaceData, DeleteWorkspaceResponses, DownloadTaskAttachmentData, DownloadTaskAttachmentResponses, GetMeData, GetMeResponses, GetProjectData, GetProjectMembersData, GetProjectMembersResponses, GetProjectResponses, GetProjectsData, GetProjectsResponses, GetSectionData, GetSectionResponses, GetSectionsData, GetSectionsResponses, GetSubtaskData, GetSubtaskResponses, GetSubtasksData, GetSubtasksResponses, GetTaskAttachmentData, GetTaskAttachmentResponses, GetTaskAttachmentsData, GetTaskAttachmentsResponses, GetTaskData, GetTaskResponses, GetTasksData, GetTasksResponses, GetUserData, GetUserResponses, GetUsersData, GetUsersResponses, GetWorkspaceData, GetWorkspaceResponses, GetWorkspacesData, GetWorkspacesResponses, LoginData, LoginResponses, LogoutData, LogoutResponses, MoveSectionData, MoveSectionResponses, MoveTaskData, MoveTaskResponses, RegisterData, RegisterResponses, SwitchData, SwitchResponses, UpdateMeData, UpdateMeResponses, UpdateProjectData, UpdateProjectResponses, UpdateSectionData, UpdateSectionResponses, UpdateSubtaskData, UpdateSubtaskResponses, UpdateTaskData, UpdateTaskResponses, UpdateUserData, UpdateUserResponses, UpdateWorkspaceData, UpdateWorkspaceResponses, UploadAvatarData, UploadAvatarResponses, UploadTaskAttachmentData, UploadTaskAttachmentResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const register = <ThrowOnError extends boolean = true>(options: Options<RegisterData, ThrowOnError>): RequestResult<RegisterResponses, unknown, ThrowOnError> => (options.client ?? client).post<RegisterResponses, unknown, ThrowOnError>({
    url: '/api/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const login = <ThrowOnError extends boolean = true>(options: Options<LoginData, ThrowOnError>): RequestResult<LoginResponses, unknown, ThrowOnError> => (options.client ?? client).post<LoginResponses, unknown, ThrowOnError>({
    url: '/api/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const logout = <ThrowOnError extends boolean = true>(options?: Options<LogoutData, ThrowOnError>): RequestResult<LogoutResponses, unknown, ThrowOnError> => (options?.client ?? client).post<LogoutResponses, unknown, ThrowOnError>({ url: '/api/auth/logout', ...options });

export const switch_ = <ThrowOnError extends boolean = true>(options: Options<SwitchData, ThrowOnError>): RequestResult<SwitchResponses, unknown, ThrowOnError> => (options.client ?? client).patch<SwitchResponses, unknown, ThrowOnError>({ url: '/api/auth/switch/{workspaceId}', ...options });

export const getMe = <ThrowOnError extends boolean = true>(options?: Options<GetMeData, ThrowOnError>): RequestResult<GetMeResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetMeResponses, unknown, ThrowOnError>({ url: '/api/auth/me', ...options });

export const updateMe = <ThrowOnError extends boolean = true>(options: Options<UpdateMeData, ThrowOnError>): RequestResult<UpdateMeResponses, unknown, ThrowOnError> => (options.client ?? client).post<UpdateMeResponses, unknown, ThrowOnError>({
    url: '/api/auth/me',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const uploadAvatar = <ThrowOnError extends boolean = true>(options: Options<UploadAvatarData, ThrowOnError>): RequestResult<UploadAvatarResponses, unknown, ThrowOnError> => (options.client ?? client).post<UploadAvatarResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/auth/me/avatar',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

export const deleteFavorite = <ThrowOnError extends boolean = true>(options: Options<DeleteFavoriteData, ThrowOnError>): RequestResult<DeleteFavoriteResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteFavoriteResponses, unknown, ThrowOnError>({ url: '/api/workspaces/{workspaceId}/favorites/{entityId}', ...options });

export const createFavorite = <ThrowOnError extends boolean = true>(options: Options<CreateFavoriteData, ThrowOnError>): RequestResult<CreateFavoriteResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateFavoriteResponses, unknown, ThrowOnError>({ url: '/api/workspaces/{workspaceId}/favorites/{entityId}', ...options });

export const getProjects = <ThrowOnError extends boolean = true>(options: Options<GetProjectsData, ThrowOnError>): RequestResult<GetProjectsResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetProjectsResponses, unknown, ThrowOnError>({ url: '/api/workspaces/{workspaceId}/projects', ...options });

export const createProject = <ThrowOnError extends boolean = true>(options: Options<CreateProjectData, ThrowOnError>): RequestResult<CreateProjectResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateProjectResponses, unknown, ThrowOnError>({
    url: '/api/workspaces/{workspaceId}/projects',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteProject = <ThrowOnError extends boolean = true>(options: Options<DeleteProjectData, ThrowOnError>): RequestResult<DeleteProjectResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteProjectResponses, unknown, ThrowOnError>({ url: '/api/workspaces/{workspaceId}/projects/{projectId}', ...options });

export const getProject = <ThrowOnError extends boolean = true>(options: Options<GetProjectData, ThrowOnError>): RequestResult<GetProjectResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetProjectResponses, unknown, ThrowOnError>({ url: '/api/workspaces/{workspaceId}/projects/{projectId}', ...options });

export const updateProject = <ThrowOnError extends boolean = true>(options: Options<UpdateProjectData, ThrowOnError>): RequestResult<UpdateProjectResponses, unknown, ThrowOnError> => (options.client ?? client).put<UpdateProjectResponses, unknown, ThrowOnError>({
    url: '/api/workspaces/{workspaceId}/projects/{projectId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getProjectMembers = <ThrowOnError extends boolean = true>(options: Options<GetProjectMembersData, ThrowOnError>): RequestResult<GetProjectMembersResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetProjectMembersResponses, unknown, ThrowOnError>({ url: '/api/workspaces/{workspaceId}/projects/{projectId}/members', ...options });

export const getSections = <ThrowOnError extends boolean = true>(options: Options<GetSectionsData, ThrowOnError>): RequestResult<GetSectionsResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetSectionsResponses, unknown, ThrowOnError>({ url: '/api/workspaces/{workspaceId}/projects/{projectId}/sections', ...options });

export const createSection = <ThrowOnError extends boolean = true>(options: Options<CreateSectionData, ThrowOnError>): RequestResult<CreateSectionResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateSectionResponses, unknown, ThrowOnError>({
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/sections',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteSection = <ThrowOnError extends boolean = true>(options: Options<DeleteSectionData, ThrowOnError>): RequestResult<DeleteSectionResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteSectionResponses, unknown, ThrowOnError>({ url: '/api/workspaces/{workspaceId}/projects/{projectId}/sections/{sectionId}', ...options });

export const getSection = <ThrowOnError extends boolean = true>(options: Options<GetSectionData, ThrowOnError>): RequestResult<GetSectionResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetSectionResponses, unknown, ThrowOnError>({ url: '/api/workspaces/{workspaceId}/projects/{projectId}/sections/{sectionId}', ...options });

export const updateSection = <ThrowOnError extends boolean = true>(options: Options<UpdateSectionData, ThrowOnError>): RequestResult<UpdateSectionResponses, unknown, ThrowOnError> => (options.client ?? client).put<UpdateSectionResponses, unknown, ThrowOnError>({
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/sections/{sectionId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const moveSection = <ThrowOnError extends boolean = true>(options: Options<MoveSectionData, ThrowOnError>): RequestResult<MoveSectionResponses, unknown, ThrowOnError> => (options.client ?? client).patch<MoveSectionResponses, unknown, ThrowOnError>({
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/sections/{sectionId}/move',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getSubtasks = <ThrowOnError extends boolean = true>(options: Options<GetSubtasksData, ThrowOnError>): RequestResult<GetSubtasksResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetSubtasksResponses, unknown, ThrowOnError>({ url: '/api/workspaces/{workspaceId}/projects/{projectId}/tasks/{taskId}/subtasks', ...options });

export const createSubtask = <ThrowOnError extends boolean = true>(options: Options<CreateSubtaskData, ThrowOnError>): RequestResult<CreateSubtaskResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateSubtaskResponses, unknown, ThrowOnError>({
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/tasks/{taskId}/subtasks',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteSubtask = <ThrowOnError extends boolean = true>(options: Options<DeleteSubtaskData, ThrowOnError>): RequestResult<DeleteSubtaskResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteSubtaskResponses, unknown, ThrowOnError>({ url: '/api/workspaces/{workspaceId}/projects/{projectId}/tasks/{taskId}/subtasks/{subtaskId}', ...options });

export const getSubtask = <ThrowOnError extends boolean = true>(options: Options<GetSubtaskData, ThrowOnError>): RequestResult<GetSubtaskResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetSubtaskResponses, unknown, ThrowOnError>({ url: '/api/workspaces/{workspaceId}/projects/{projectId}/tasks/{taskId}/subtasks/{subtaskId}', ...options });

export const updateSubtask = <ThrowOnError extends boolean = true>(options: Options<UpdateSubtaskData, ThrowOnError>): RequestResult<UpdateSubtaskResponses, unknown, ThrowOnError> => (options.client ?? client).put<UpdateSubtaskResponses, unknown, ThrowOnError>({
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/tasks/{taskId}/subtasks/{subtaskId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getTaskAttachments = <ThrowOnError extends boolean = true>(options: Options<GetTaskAttachmentsData, ThrowOnError>): RequestResult<GetTaskAttachmentsResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetTaskAttachmentsResponses, unknown, ThrowOnError>({ url: '/api/workspaces/{workspaceId}/projects/{projectId}/tasks/{taskId}/attachments', ...options });

export const uploadTaskAttachment = <ThrowOnError extends boolean = true>(options: Options<UploadTaskAttachmentData, ThrowOnError>): RequestResult<UploadTaskAttachmentResponses, unknown, ThrowOnError> => (options.client ?? client).post<UploadTaskAttachmentResponses, unknown, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/tasks/{taskId}/attachments',
    ...options,
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        ...options.headers
    }
});

export const deleteTaskAttachment = <ThrowOnError extends boolean = true>(options: Options<DeleteTaskAttachmentData, ThrowOnError>): RequestResult<DeleteTaskAttachmentResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteTaskAttachmentResponses, unknown, ThrowOnError>({ url: '/api/workspaces/{workspaceId}/projects/{projectId}/tasks/{taskId}/attachments/{attachmentId}', ...options });

export const getTaskAttachment = <ThrowOnError extends boolean = true>(options: Options<GetTaskAttachmentData, ThrowOnError>): RequestResult<GetTaskAttachmentResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetTaskAttachmentResponses, unknown, ThrowOnError>({ url: '/api/workspaces/{workspaceId}/projects/{projectId}/tasks/{taskId}/attachments/{attachmentId}', ...options });

export const downloadTaskAttachment = <ThrowOnError extends boolean = true>(options: Options<DownloadTaskAttachmentData, ThrowOnError>): RequestResult<DownloadTaskAttachmentResponses, unknown, ThrowOnError> => (options.client ?? client).get<DownloadTaskAttachmentResponses, unknown, ThrowOnError>({ url: '/api/workspaces/{workspaceId}/projects/{projectId}/tasks/{taskId}/attachments/{attachmentId}/download', ...options });

export const getTasks = <ThrowOnError extends boolean = true>(options: Options<GetTasksData, ThrowOnError>): RequestResult<GetTasksResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetTasksResponses, unknown, ThrowOnError>({ url: '/api/workspaces/{workspaceId}/projects/{projectId}/tasks', ...options });

export const createTask = <ThrowOnError extends boolean = true>(options: Options<CreateTaskData, ThrowOnError>): RequestResult<CreateTaskResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateTaskResponses, unknown, ThrowOnError>({
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/tasks',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteTask = <ThrowOnError extends boolean = true>(options: Options<DeleteTaskData, ThrowOnError>): RequestResult<DeleteTaskResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteTaskResponses, unknown, ThrowOnError>({ url: '/api/workspaces/{workspaceId}/projects/{projectId}/tasks/{taskId}', ...options });

export const getTask = <ThrowOnError extends boolean = true>(options: Options<GetTaskData, ThrowOnError>): RequestResult<GetTaskResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetTaskResponses, unknown, ThrowOnError>({ url: '/api/workspaces/{workspaceId}/projects/{projectId}/tasks/{taskId}', ...options });

export const updateTask = <ThrowOnError extends boolean = true>(options: Options<UpdateTaskData, ThrowOnError>): RequestResult<UpdateTaskResponses, unknown, ThrowOnError> => (options.client ?? client).put<UpdateTaskResponses, unknown, ThrowOnError>({
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/tasks/{taskId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const moveTask = <ThrowOnError extends boolean = true>(options: Options<MoveTaskData, ThrowOnError>): RequestResult<MoveTaskResponses, unknown, ThrowOnError> => (options.client ?? client).patch<MoveTaskResponses, unknown, ThrowOnError>({
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/tasks/{taskId}/move',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getUsers = <ThrowOnError extends boolean = true>(options: Options<GetUsersData, ThrowOnError>): RequestResult<GetUsersResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetUsersResponses, unknown, ThrowOnError>({ url: '/api/workspaces/{workspaceId}/users', ...options });

export const createUser = <ThrowOnError extends boolean = true>(options: Options<CreateUserData, ThrowOnError>): RequestResult<CreateUserResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateUserResponses, unknown, ThrowOnError>({
    url: '/api/workspaces/{workspaceId}/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteUser = <ThrowOnError extends boolean = true>(options: Options<DeleteUserData, ThrowOnError>): RequestResult<DeleteUserResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteUserResponses, unknown, ThrowOnError>({ url: '/api/workspaces/{workspaceId}/users/{userId}', ...options });

export const getUser = <ThrowOnError extends boolean = true>(options: Options<GetUserData, ThrowOnError>): RequestResult<GetUserResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetUserResponses, unknown, ThrowOnError>({ url: '/api/workspaces/{workspaceId}/users/{userId}', ...options });

export const updateUser = <ThrowOnError extends boolean = true>(options: Options<UpdateUserData, ThrowOnError>): RequestResult<UpdateUserResponses, unknown, ThrowOnError> => (options.client ?? client).put<UpdateUserResponses, unknown, ThrowOnError>({
    url: '/api/workspaces/{workspaceId}/users/{userId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getWorkspaces = <ThrowOnError extends boolean = true>(options?: Options<GetWorkspacesData, ThrowOnError>): RequestResult<GetWorkspacesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetWorkspacesResponses, unknown, ThrowOnError>({ url: '/api/Workspaces', ...options });

export const createWorkspace = <ThrowOnError extends boolean = true>(options: Options<CreateWorkspaceData, ThrowOnError>): RequestResult<CreateWorkspaceResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateWorkspaceResponses, unknown, ThrowOnError>({
    url: '/api/Workspaces',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteWorkspace = <ThrowOnError extends boolean = true>(options: Options<DeleteWorkspaceData, ThrowOnError>): RequestResult<DeleteWorkspaceResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteWorkspaceResponses, unknown, ThrowOnError>({ url: '/api/Workspaces/{workspaceId}', ...options });

export const getWorkspace = <ThrowOnError extends boolean = true>(options: Options<GetWorkspaceData, ThrowOnError>): RequestResult<GetWorkspaceResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetWorkspaceResponses, unknown, ThrowOnError>({ url: '/api/Workspaces/{workspaceId}', ...options });

export const updateWorkspace = <ThrowOnError extends boolean = true>(options: Options<UpdateWorkspaceData, ThrowOnError>): RequestResult<UpdateWorkspaceResponses, unknown, ThrowOnError> => (options.client ?? client).put<UpdateWorkspaceResponses, unknown, ThrowOnError>({
    url: '/api/Workspaces/{workspaceId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
