// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5197/' | (string & {});
};

export type EFavoriteEntityType = 'Project';

export type EPriority = 'None' | 'Low' | 'Medium' | 'High';

export type EProjectRole = 'Member' | 'Lead' | 'Owner';

export type EProjectStatus = 'Planning' | 'Active' | 'OnHold' | 'Archived';

export type EWorkspaceRole = 'Member' | 'Manager' | 'Admin' | 'Owner';

export type IFormFile = Blob | File;

export type JsonElement = unknown;

export type LoginRequest = {
    email: string;
    password: string;
    rememberMe?: boolean;
};

export type MeDto = {
    id: string;
    email: string;
    firstName: string;
    lastName?: null | string;
    fullName?: null | string;
    avatarUrl?: null | string;
    activeWorkspace?: null | WorkspaceDto;
};

export type MeRequest = {
    firstName: string;
    lastName?: null | string;
};

export type MoveSectionRequest = {
    previousSectionId?: null | string;
    nextSectionId?: null | string;
};

export type MoveTaskRequest = {
    sectionId: string;
    previousTaskId?: null | string;
    nextTaskId?: null | string;
};

export type ProjectDto = {
    id: string;
    name: string;
    description?: null | string;
    priority: EPriority;
    status: EProjectStatus;
    dueDate?: null | string;
    role?: null | EProjectRole;
    team: Array<ProjectMemberDto>;
};

export type ProjectMemberDto = {
    id: string;
    email: string;
    firstName: string;
    lastName?: null | string;
    fullName?: null | string;
    avatarUrl?: null | string;
    role: EProjectRole;
};

export type ProjectRequest = {
    name: string;
    description?: null | string;
    priority: EPriority;
    status: EProjectStatus;
    dueDate?: null | string;
    leadIds?: null | Array<string>;
    memberIds?: null | Array<string>;
};

export type RegisterRequest = {
    email: string;
    password: string;
    firstName: string;
    lastName?: null | string;
};

export type Response = {
    message: string;
};

export type ResponseOfListOfProjectDto = {
    data?: null | Array<ProjectDto>;
    message?: string;
};

export type ResponseOfListOfProjectMemberDto = {
    data?: null | Array<ProjectMemberDto>;
    message?: string;
};

export type ResponseOfListOfSectionDto = {
    data?: null | Array<SectionDto>;
    message?: string;
};

export type ResponseOfListOfSubtaskDto = {
    data?: null | Array<SubtaskDto>;
    message?: string;
};

export type ResponseOfListOfTaskAttachmentDto = {
    data?: null | Array<TaskAttachmentDto>;
    message?: string;
};

export type ResponseOfListOfUserDto = {
    data?: null | Array<UserDto>;
    message?: string;
};

export type ResponseOfListOfWorkspaceDto = {
    data?: null | Array<WorkspaceDto>;
    message?: string;
};

export type ResponseOfMeDto = {
    data?: MeDto;
    message?: string;
};

export type ResponseOfProjectDto = {
    data?: ProjectDto;
    message?: string;
};

export type ResponseOfSectionDto = {
    data?: SectionDto;
    message?: string;
};

export type ResponseOfSubtaskDto = {
    data?: SubtaskDto;
    message?: string;
};

export type ResponseOfTaskAttachmentDto = {
    data?: TaskAttachmentDto;
    message?: string;
};

export type ResponseOfTaskDto = {
    data?: TaskDto;
    message?: string;
};

export type ResponseOfTaskDto2 = {
    data?: null | Array<TaskDto>;
    message?: string;
};

export type ResponseOfTaskLabelDto = {
    data?: TaskLabelDto;
    message?: string;
};

export type ResponseOfTaskLabelDto2 = {
    data?: null | Array<TaskLabelDto>;
    message?: string;
};

export type ResponseOfTaskTypeDto = {
    data?: TaskTypeDto;
    message?: string;
};

export type ResponseOfTaskTypeDto2 = {
    data?: null | Array<TaskTypeDto>;
    message?: string;
};

export type ResponseOfUserDto = {
    data?: UserDto;
    message?: string;
};

export type ResponseOfWorkspaceDto = {
    data?: WorkspaceDto;
    message?: string;
};

export type SectionDto = {
    id: string;
    name: string;
};

export type SectionRequest = {
    name: string;
};

export type SubtaskDto = {
    id: string;
    name: string;
    position: number;
    completedAt?: null | string;
};

export type SubtaskRequest = {
    name: string;
    previousSubtaskId?: null | string;
    nextSubtaskId?: null | string;
    isCompleted?: boolean;
};

export type TaskAttachmentDto = {
    id: string;
    fileName: string;
    contentType: string;
    sizeBytes: number;
    downloadUrl: string;
};

export type TaskDto = {
    id: string;
    sectionId: string;
    refId: number;
    name: string;
    description?: null | JsonElement;
    position: number;
    priority: EPriority;
    dueDate?: null | string;
    completedAt?: null | string;
    assignee?: null | ProjectMemberDto;
    assignedAt?: null | string;
    taskType?: null | TaskTypeDto;
    taskLabels: Array<TaskLabelDto>;
    attachments: Array<TaskAttachmentDto>;
    subtasks: Array<SubtaskDto>;
};

export type TaskLabelDto = {
    id: string;
    name: string;
};

export type TaskLabelRequest = {
    name: string;
};

export type TaskRequest = {
    sectionId: string;
    name: string;
    description?: null | JsonElement;
    priority: EPriority;
    dueDate?: null | string;
    taskTypeId?: null | string;
    taskLabelIds?: Array<string>;
    assigneeId?: null | string;
    previousTaskId?: null | string;
    nextTaskId?: null | string;
};

export type TaskTypeDto = {
    id: string;
    name: string;
    code: string;
};

export type TaskTypeRequest = {
    name: string;
    code: string;
};

export type UserDto = {
    id: string;
    email: string;
    firstName: string;
    lastName?: null | string;
    fullName?: null | string;
    avatarUrl?: null | string;
    role: EWorkspaceRole;
};

export type UserRequest = {
    email: string;
    role: EWorkspaceRole;
};

export type WorkspaceDto = {
    id: string;
    name: string;
    role: EWorkspaceRole;
    isPersonalWorkspace?: boolean;
    memberCount: number;
};

export type WorkspaceRequest = {
    name: string;
};

export type RegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type RegisterResponses = {
    /**
     * OK
     */
    200: Response;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginResponses = {
    /**
     * OK
     */
    200: ResponseOfMeDto;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutResponses = {
    /**
     * OK
     */
    200: Response;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type SwitchData = {
    body?: never;
    path: {
        workspaceId: string;
    };
    query?: never;
    url: '/api/auth/switch/{workspaceId}';
};

export type SwitchResponses = {
    /**
     * OK
     */
    200: ResponseOfMeDto;
};

export type SwitchResponse = SwitchResponses[keyof SwitchResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type GetMeResponses = {
    /**
     * OK
     */
    200: ResponseOfMeDto;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type UpdateMeData = {
    body: MeRequest;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type UpdateMeResponses = {
    /**
     * OK
     */
    200: ResponseOfMeDto;
};

export type UpdateMeResponse = UpdateMeResponses[keyof UpdateMeResponses];

export type UploadAvatarData = {
    body: {
        avatar?: IFormFile;
    };
    path?: never;
    query?: never;
    url: '/api/auth/me/avatar';
};

export type UploadAvatarResponses = {
    /**
     * OK
     */
    200: ResponseOfMeDto;
};

export type UploadAvatarResponse = UploadAvatarResponses[keyof UploadAvatarResponses];

export type DeleteFavoriteData = {
    body?: never;
    path: {
        workspaceId: string;
        entityId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/favorites/{entityId}';
};

export type DeleteFavoriteResponses = {
    /**
     * OK
     */
    200: Response;
};

export type DeleteFavoriteResponse = DeleteFavoriteResponses[keyof DeleteFavoriteResponses];

export type CreateFavoriteData = {
    body?: never;
    path: {
        workspaceId: string;
        entityId: string;
    };
    query: {
        entityType: EFavoriteEntityType;
    };
    url: '/api/workspaces/{workspaceId}/favorites/{entityId}';
};

export type CreateFavoriteResponses = {
    /**
     * OK
     */
    200: Response;
};

export type CreateFavoriteResponse = CreateFavoriteResponses[keyof CreateFavoriteResponses];

export type GetProjectsData = {
    body?: never;
    path: {
        workspaceId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/projects';
};

export type GetProjectsResponses = {
    /**
     * OK
     */
    200: ResponseOfListOfProjectDto;
};

export type GetProjectsResponse = GetProjectsResponses[keyof GetProjectsResponses];

export type CreateProjectData = {
    body: ProjectRequest;
    path: {
        workspaceId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/projects';
};

export type CreateProjectResponses = {
    /**
     * OK
     */
    200: ResponseOfProjectDto;
};

export type CreateProjectResponse = CreateProjectResponses[keyof CreateProjectResponses];

export type DeleteProjectData = {
    body?: never;
    path: {
        workspaceId: string;
        projectId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/projects/{projectId}';
};

export type DeleteProjectResponses = {
    /**
     * OK
     */
    200: Response;
};

export type DeleteProjectResponse = DeleteProjectResponses[keyof DeleteProjectResponses];

export type GetProjectData = {
    body?: never;
    path: {
        workspaceId: string;
        projectId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/projects/{projectId}';
};

export type GetProjectResponses = {
    /**
     * OK
     */
    200: ResponseOfProjectDto;
};

export type GetProjectResponse = GetProjectResponses[keyof GetProjectResponses];

export type UpdateProjectData = {
    body: ProjectRequest;
    path: {
        workspaceId: string;
        projectId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/projects/{projectId}';
};

export type UpdateProjectResponses = {
    /**
     * OK
     */
    200: ResponseOfProjectDto;
};

export type UpdateProjectResponse = UpdateProjectResponses[keyof UpdateProjectResponses];

export type GetProjectMembersData = {
    body?: never;
    path: {
        workspaceId: string;
        projectId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/members';
};

export type GetProjectMembersResponses = {
    /**
     * OK
     */
    200: ResponseOfListOfProjectMemberDto;
};

export type GetProjectMembersResponse = GetProjectMembersResponses[keyof GetProjectMembersResponses];

export type GetSectionsData = {
    body?: never;
    path: {
        workspaceId: string;
        projectId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/sections';
};

export type GetSectionsResponses = {
    /**
     * OK
     */
    200: ResponseOfListOfSectionDto;
};

export type GetSectionsResponse = GetSectionsResponses[keyof GetSectionsResponses];

export type CreateSectionData = {
    body: SectionRequest;
    path: {
        workspaceId: string;
        projectId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/sections';
};

export type CreateSectionResponses = {
    /**
     * OK
     */
    200: ResponseOfSectionDto;
};

export type CreateSectionResponse = CreateSectionResponses[keyof CreateSectionResponses];

export type DeleteSectionData = {
    body?: never;
    path: {
        workspaceId: string;
        projectId: string;
        sectionId: string;
    };
    query?: {
        moveTasksTo?: string;
        deleteTasks?: boolean;
    };
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/sections/{sectionId}';
};

export type DeleteSectionResponses = {
    /**
     * OK
     */
    200: ResponseOfSectionDto;
};

export type DeleteSectionResponse = DeleteSectionResponses[keyof DeleteSectionResponses];

export type GetSectionData = {
    body?: never;
    path: {
        workspaceId: string;
        projectId: string;
        sectionId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/sections/{sectionId}';
};

export type GetSectionResponses = {
    /**
     * OK
     */
    200: ResponseOfSectionDto;
};

export type GetSectionResponse = GetSectionResponses[keyof GetSectionResponses];

export type UpdateSectionData = {
    body: SectionRequest;
    path: {
        workspaceId: string;
        projectId: string;
        sectionId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/sections/{sectionId}';
};

export type UpdateSectionResponses = {
    /**
     * OK
     */
    200: ResponseOfSectionDto;
};

export type UpdateSectionResponse = UpdateSectionResponses[keyof UpdateSectionResponses];

export type MoveSectionData = {
    body: MoveSectionRequest;
    path: {
        workspaceId: string;
        projectId: string;
        sectionId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/sections/{sectionId}/move';
};

export type MoveSectionResponses = {
    /**
     * OK
     */
    200: Response;
};

export type MoveSectionResponse = MoveSectionResponses[keyof MoveSectionResponses];

export type GetSubtasksData = {
    body?: never;
    path: {
        workspaceId: string;
        projectId: string;
        taskId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/tasks/{taskId}/subtasks';
};

export type GetSubtasksResponses = {
    /**
     * OK
     */
    200: ResponseOfListOfSubtaskDto;
};

export type GetSubtasksResponse = GetSubtasksResponses[keyof GetSubtasksResponses];

export type CreateSubtaskData = {
    body: SubtaskRequest;
    path: {
        workspaceId: string;
        projectId: string;
        taskId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/tasks/{taskId}/subtasks';
};

export type CreateSubtaskResponses = {
    /**
     * OK
     */
    200: ResponseOfSubtaskDto;
};

export type CreateSubtaskResponse = CreateSubtaskResponses[keyof CreateSubtaskResponses];

export type DeleteSubtaskData = {
    body?: never;
    path: {
        workspaceId: string;
        projectId: string;
        taskId: string;
        subtaskId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/tasks/{taskId}/subtasks/{subtaskId}';
};

export type DeleteSubtaskResponses = {
    /**
     * OK
     */
    200: Response;
};

export type DeleteSubtaskResponse = DeleteSubtaskResponses[keyof DeleteSubtaskResponses];

export type GetSubtaskData = {
    body?: never;
    path: {
        workspaceId: string;
        projectId: string;
        taskId: string;
        subtaskId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/tasks/{taskId}/subtasks/{subtaskId}';
};

export type GetSubtaskResponses = {
    /**
     * OK
     */
    200: ResponseOfSubtaskDto;
};

export type GetSubtaskResponse = GetSubtaskResponses[keyof GetSubtaskResponses];

export type UpdateSubtaskData = {
    body: SubtaskRequest;
    path: {
        workspaceId: string;
        projectId: string;
        taskId: string;
        subtaskId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/tasks/{taskId}/subtasks/{subtaskId}';
};

export type UpdateSubtaskResponses = {
    /**
     * OK
     */
    200: ResponseOfSubtaskDto;
};

export type UpdateSubtaskResponse = UpdateSubtaskResponses[keyof UpdateSubtaskResponses];

export type GetTaskAttachmentsData = {
    body?: never;
    path: {
        workspaceId: string;
        projectId: string;
        taskId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/tasks/{taskId}/attachments';
};

export type GetTaskAttachmentsResponses = {
    /**
     * OK
     */
    200: ResponseOfListOfTaskAttachmentDto;
};

export type GetTaskAttachmentsResponse = GetTaskAttachmentsResponses[keyof GetTaskAttachmentsResponses];

export type UploadTaskAttachmentData = {
    body: {
        File?: IFormFile;
    };
    path: {
        workspaceId: string;
        projectId: string;
        taskId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/tasks/{taskId}/attachments';
};

export type UploadTaskAttachmentResponses = {
    /**
     * OK
     */
    200: ResponseOfTaskAttachmentDto;
};

export type UploadTaskAttachmentResponse = UploadTaskAttachmentResponses[keyof UploadTaskAttachmentResponses];

export type DeleteTaskAttachmentData = {
    body?: never;
    path: {
        workspaceId: string;
        projectId: string;
        taskId: string;
        attachmentId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/tasks/{taskId}/attachments/{attachmentId}';
};

export type DeleteTaskAttachmentResponses = {
    /**
     * OK
     */
    200: Response;
};

export type DeleteTaskAttachmentResponse = DeleteTaskAttachmentResponses[keyof DeleteTaskAttachmentResponses];

export type GetTaskAttachmentData = {
    body?: never;
    path: {
        workspaceId: string;
        projectId: string;
        taskId: string;
        attachmentId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/tasks/{taskId}/attachments/{attachmentId}';
};

export type GetTaskAttachmentResponses = {
    /**
     * OK
     */
    200: ResponseOfTaskAttachmentDto;
};

export type GetTaskAttachmentResponse = GetTaskAttachmentResponses[keyof GetTaskAttachmentResponses];

export type DownloadTaskAttachmentData = {
    body?: never;
    path: {
        workspaceId: string;
        projectId: string;
        taskId: string;
        attachmentId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/tasks/{taskId}/attachments/{attachmentId}/download';
};

export type DownloadTaskAttachmentResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetTaskLabelsData = {
    body?: never;
    path: {
        workspaceId: string;
        projectId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/task-labels';
};

export type GetTaskLabelsResponses = {
    /**
     * OK
     */
    200: ResponseOfTaskLabelDto2;
};

export type GetTaskLabelsResponse = GetTaskLabelsResponses[keyof GetTaskLabelsResponses];

export type CreateTaskLabelData = {
    body: TaskLabelRequest;
    path: {
        workspaceId: string;
        projectId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/task-labels';
};

export type CreateTaskLabelResponses = {
    /**
     * OK
     */
    200: ResponseOfTaskLabelDto;
};

export type CreateTaskLabelResponse = CreateTaskLabelResponses[keyof CreateTaskLabelResponses];

export type DeleteTaskLabelData = {
    body?: never;
    path: {
        workspaceId: string;
        projectId: string;
        taskTypeId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/task-labels/{taskTypeId}';
};

export type DeleteTaskLabelResponses = {
    /**
     * OK
     */
    200: Response;
};

export type DeleteTaskLabelResponse = DeleteTaskLabelResponses[keyof DeleteTaskLabelResponses];

export type GetTaskLabelData = {
    body?: never;
    path: {
        workspaceId: string;
        projectId: string;
        taskTypeId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/task-labels/{taskTypeId}';
};

export type GetTaskLabelResponses = {
    /**
     * OK
     */
    200: ResponseOfTaskLabelDto;
};

export type GetTaskLabelResponse = GetTaskLabelResponses[keyof GetTaskLabelResponses];

export type UpdateTaskLabelData = {
    body: TaskLabelRequest;
    path: {
        workspaceId: string;
        projectId: string;
        taskTypeId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/task-labels/{taskTypeId}';
};

export type UpdateTaskLabelResponses = {
    /**
     * OK
     */
    200: ResponseOfTaskLabelDto;
};

export type UpdateTaskLabelResponse = UpdateTaskLabelResponses[keyof UpdateTaskLabelResponses];

export type GetTasksData = {
    body?: never;
    path: {
        workspaceId: string;
        projectId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/tasks';
};

export type GetTasksResponses = {
    /**
     * OK
     */
    200: ResponseOfTaskDto2;
};

export type GetTasksResponse = GetTasksResponses[keyof GetTasksResponses];

export type CreateTaskData = {
    body: TaskRequest;
    path: {
        workspaceId: string;
        projectId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/tasks';
};

export type CreateTaskResponses = {
    /**
     * OK
     */
    200: ResponseOfTaskDto;
};

export type CreateTaskResponse = CreateTaskResponses[keyof CreateTaskResponses];

export type DeleteTaskData = {
    body?: never;
    path: {
        workspaceId: string;
        projectId: string;
        taskId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/tasks/{taskId}';
};

export type DeleteTaskResponses = {
    /**
     * OK
     */
    200: Response;
};

export type DeleteTaskResponse = DeleteTaskResponses[keyof DeleteTaskResponses];

export type GetTaskData = {
    body?: never;
    path: {
        workspaceId: string;
        projectId: string;
        taskId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/tasks/{taskId}';
};

export type GetTaskResponses = {
    /**
     * OK
     */
    200: ResponseOfTaskDto;
};

export type GetTaskResponse = GetTaskResponses[keyof GetTaskResponses];

export type UpdateTaskData = {
    body: TaskRequest;
    path: {
        workspaceId: string;
        projectId: string;
        taskId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/tasks/{taskId}';
};

export type UpdateTaskResponses = {
    /**
     * OK
     */
    200: ResponseOfTaskDto;
};

export type UpdateTaskResponse = UpdateTaskResponses[keyof UpdateTaskResponses];

export type MoveTaskData = {
    body: MoveTaskRequest;
    path: {
        workspaceId: string;
        projectId: string;
        taskId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/tasks/{taskId}/move';
};

export type MoveTaskResponses = {
    /**
     * OK
     */
    200: ResponseOfTaskDto;
};

export type MoveTaskResponse = MoveTaskResponses[keyof MoveTaskResponses];

export type GetTaskTypesData = {
    body?: never;
    path: {
        workspaceId: string;
        projectId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/task-types';
};

export type GetTaskTypesResponses = {
    /**
     * OK
     */
    200: ResponseOfTaskTypeDto2;
};

export type GetTaskTypesResponse = GetTaskTypesResponses[keyof GetTaskTypesResponses];

export type CreateTaskTypeData = {
    body: TaskTypeRequest;
    path: {
        workspaceId: string;
        projectId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/task-types';
};

export type CreateTaskTypeResponses = {
    /**
     * OK
     */
    200: ResponseOfTaskTypeDto;
};

export type CreateTaskTypeResponse = CreateTaskTypeResponses[keyof CreateTaskTypeResponses];

export type DeleteTaskTypeData = {
    body?: never;
    path: {
        workspaceId: string;
        projectId: string;
        taskTypeId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/task-types/{taskTypeId}';
};

export type DeleteTaskTypeResponses = {
    /**
     * OK
     */
    200: Response;
};

export type DeleteTaskTypeResponse = DeleteTaskTypeResponses[keyof DeleteTaskTypeResponses];

export type GetTaskTypeData = {
    body?: never;
    path: {
        workspaceId: string;
        projectId: string;
        taskTypeId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/task-types/{taskTypeId}';
};

export type GetTaskTypeResponses = {
    /**
     * OK
     */
    200: ResponseOfTaskTypeDto;
};

export type GetTaskTypeResponse = GetTaskTypeResponses[keyof GetTaskTypeResponses];

export type UpdateTaskTypeData = {
    body: TaskTypeRequest;
    path: {
        workspaceId: string;
        projectId: string;
        taskTypeId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/projects/{projectId}/task-types/{taskTypeId}';
};

export type UpdateTaskTypeResponses = {
    /**
     * OK
     */
    200: ResponseOfTaskTypeDto;
};

export type UpdateTaskTypeResponse = UpdateTaskTypeResponses[keyof UpdateTaskTypeResponses];

export type GetUsersData = {
    body?: never;
    path: {
        workspaceId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/users';
};

export type GetUsersResponses = {
    /**
     * OK
     */
    200: ResponseOfListOfUserDto;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type CreateUserData = {
    body: UserRequest;
    path: {
        workspaceId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/users';
};

export type CreateUserResponses = {
    /**
     * OK
     */
    200: ResponseOfUserDto;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type DeleteUserData = {
    body?: never;
    path: {
        workspaceId: string;
        userId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/users/{userId}';
};

export type DeleteUserResponses = {
    /**
     * OK
     */
    200: Response;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type GetUserData = {
    body?: never;
    path: {
        workspaceId: string;
        userId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/users/{userId}';
};

export type GetUserResponses = {
    /**
     * OK
     */
    200: ResponseOfUserDto;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type UpdateUserData = {
    body: UserRequest;
    path: {
        workspaceId: string;
        userId: string;
    };
    query?: never;
    url: '/api/workspaces/{workspaceId}/users/{userId}';
};

export type UpdateUserResponses = {
    /**
     * OK
     */
    200: ResponseOfUserDto;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type GetWorkspacesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Workspaces';
};

export type GetWorkspacesResponses = {
    /**
     * OK
     */
    200: ResponseOfListOfWorkspaceDto;
};

export type GetWorkspacesResponse = GetWorkspacesResponses[keyof GetWorkspacesResponses];

export type CreateWorkspaceData = {
    body: WorkspaceRequest;
    path?: never;
    query?: never;
    url: '/api/Workspaces';
};

export type CreateWorkspaceResponses = {
    /**
     * OK
     */
    200: ResponseOfWorkspaceDto;
};

export type CreateWorkspaceResponse = CreateWorkspaceResponses[keyof CreateWorkspaceResponses];

export type DeleteWorkspaceData = {
    body?: never;
    path: {
        workspaceId: string;
    };
    query?: never;
    url: '/api/Workspaces/{workspaceId}';
};

export type DeleteWorkspaceResponses = {
    /**
     * OK
     */
    200: Response;
};

export type DeleteWorkspaceResponse = DeleteWorkspaceResponses[keyof DeleteWorkspaceResponses];

export type GetWorkspaceData = {
    body?: never;
    path: {
        workspaceId: string;
    };
    query?: never;
    url: '/api/Workspaces/{workspaceId}';
};

export type GetWorkspaceResponses = {
    /**
     * OK
     */
    200: ResponseOfWorkspaceDto;
};

export type GetWorkspaceResponse = GetWorkspaceResponses[keyof GetWorkspaceResponses];

export type UpdateWorkspaceData = {
    body: WorkspaceRequest;
    path: {
        workspaceId: string;
    };
    query?: never;
    url: '/api/Workspaces/{workspaceId}';
};

export type UpdateWorkspaceResponses = {
    /**
     * OK
     */
    200: ResponseOfWorkspaceDto;
};

export type UpdateWorkspaceResponse = UpdateWorkspaceResponses[keyof UpdateWorkspaceResponses];
