/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/Auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                    "text/json": components["schemas"]["RegisterRequest"];
                    "application/*+json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Response"];
                        "application/json": components["schemas"]["Response"];
                        "text/json": components["schemas"]["Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseOfMeDto"];
                        "application/json": components["schemas"]["ResponseOfMeDto"];
                        "text/json": components["schemas"]["ResponseOfMeDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Response"];
                        "application/json": components["schemas"]["Response"];
                        "text/json": components["schemas"]["Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Auth/switch/{workspaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseOfMeDto"];
                        "application/json": components["schemas"]["ResponseOfMeDto"];
                        "text/json": components["schemas"]["ResponseOfMeDto"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/Auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseOfMeDto"];
                        "application/json": components["schemas"]["ResponseOfMeDto"];
                        "text/json": components["schemas"]["ResponseOfMeDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MeRequest"];
                    "text/json": components["schemas"]["MeRequest"];
                    "application/*+json": components["schemas"]["MeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseOfMeDto"];
                        "application/json": components["schemas"]["ResponseOfMeDto"];
                        "text/json": components["schemas"]["ResponseOfMeDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Auth/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        avatar?: components["schemas"]["IFormFile"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseOfstring"];
                        "application/json": components["schemas"]["ResponseOfstring"];
                        "text/json": components["schemas"]["ResponseOfstring"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/Favorites/{entityId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query: {
                    entityType: components["schemas"]["EFavoriteEntityType"];
                };
                header?: never;
                path: {
                    workspaceId: string;
                    entityId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Response"];
                        "application/json": components["schemas"]["Response"];
                        "text/json": components["schemas"]["Response"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/Favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: {
                    entityId?: string;
                };
                header?: never;
                path: {
                    workspaceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Response"];
                        "application/json": components["schemas"]["Response"];
                        "text/json": components["schemas"]["Response"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/Projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseOfListOfProjectDto"];
                        "application/json": components["schemas"]["ResponseOfListOfProjectDto"];
                        "text/json": components["schemas"]["ResponseOfListOfProjectDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProjectRequest"];
                    "text/json": components["schemas"]["ProjectRequest"];
                    "application/*+json": components["schemas"]["ProjectRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseOfProjectDto"];
                        "application/json": components["schemas"]["ResponseOfProjectDto"];
                        "text/json": components["schemas"]["ResponseOfProjectDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/Projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: string;
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseOfProjectDto"];
                        "application/json": components["schemas"]["ResponseOfProjectDto"];
                        "text/json": components["schemas"]["ResponseOfProjectDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: string;
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProjectRequest"];
                    "text/json": components["schemas"]["ProjectRequest"];
                    "application/*+json": components["schemas"]["ProjectRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseOfProjectDto"];
                        "application/json": components["schemas"]["ResponseOfProjectDto"];
                        "text/json": components["schemas"]["ResponseOfProjectDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: string;
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Response"];
                        "application/json": components["schemas"]["Response"];
                        "text/json": components["schemas"]["Response"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/Projects/{projectId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: string;
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseOfListOfProjectMemberDto"];
                        "application/json": components["schemas"]["ResponseOfListOfProjectMemberDto"];
                        "text/json": components["schemas"]["ResponseOfListOfProjectMemberDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/projects/{projectId}/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: string;
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseOfListOfSectionDto"];
                        "application/json": components["schemas"]["ResponseOfListOfSectionDto"];
                        "text/json": components["schemas"]["ResponseOfListOfSectionDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: string;
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SectionRequest"];
                    "text/json": components["schemas"]["SectionRequest"];
                    "application/*+json": components["schemas"]["SectionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseOfSectionDto"];
                        "application/json": components["schemas"]["ResponseOfSectionDto"];
                        "text/json": components["schemas"]["ResponseOfSectionDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/projects/{projectId}/sections/{sectionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: string;
                    projectId: string;
                    sectionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseOfSectionDto"];
                        "application/json": components["schemas"]["ResponseOfSectionDto"];
                        "text/json": components["schemas"]["ResponseOfSectionDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: string;
                    projectId: string;
                    sectionId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SectionRequest"];
                    "text/json": components["schemas"]["SectionRequest"];
                    "application/*+json": components["schemas"]["SectionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseOfSectionDto"];
                        "application/json": components["schemas"]["ResponseOfSectionDto"];
                        "text/json": components["schemas"]["ResponseOfSectionDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: {
                    moveTasksTo?: string;
                    deleteTasks?: boolean;
                };
                header?: never;
                path: {
                    workspaceId: string;
                    projectId: string;
                    sectionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseOfSectionDto"];
                        "application/json": components["schemas"]["ResponseOfSectionDto"];
                        "text/json": components["schemas"]["ResponseOfSectionDto"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/projects/{projectId}/sections/{sectionId}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: string;
                    projectId: string;
                    sectionId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MoveSectionRequest"];
                    "text/json": components["schemas"]["MoveSectionRequest"];
                    "application/*+json": components["schemas"]["MoveSectionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Response"];
                        "application/json": components["schemas"]["Response"];
                        "text/json": components["schemas"]["Response"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/projects/{projectId}/Tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: string;
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseOfListOfTaskDto"];
                        "application/json": components["schemas"]["ResponseOfListOfTaskDto"];
                        "text/json": components["schemas"]["ResponseOfListOfTaskDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: string;
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TaskRequest"];
                    "text/json": components["schemas"]["TaskRequest"];
                    "application/*+json": components["schemas"]["TaskRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseOfTaskDto"];
                        "application/json": components["schemas"]["ResponseOfTaskDto"];
                        "text/json": components["schemas"]["ResponseOfTaskDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/projects/{projectId}/Tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: string;
                    projectId: string;
                    taskId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseOfTaskDto"];
                        "application/json": components["schemas"]["ResponseOfTaskDto"];
                        "text/json": components["schemas"]["ResponseOfTaskDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: string;
                    projectId: string;
                    taskId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TaskRequest"];
                    "text/json": components["schemas"]["TaskRequest"];
                    "application/*+json": components["schemas"]["TaskRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseOfTaskDto"];
                        "application/json": components["schemas"]["ResponseOfTaskDto"];
                        "text/json": components["schemas"]["ResponseOfTaskDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: string;
                    projectId: string;
                    taskId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Response"];
                        "application/json": components["schemas"]["Response"];
                        "text/json": components["schemas"]["Response"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/projects/{projectId}/Tasks/{taskId}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: string;
                    projectId: string;
                    taskId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MoveTaskRequest"];
                    "text/json": components["schemas"]["MoveTaskRequest"];
                    "application/*+json": components["schemas"]["MoveTaskRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Response"];
                        "application/json": components["schemas"]["Response"];
                        "text/json": components["schemas"]["Response"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/projects/{projectId}/Tasks/{taskId}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: string;
                    projectId: string;
                    taskId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseOfListOfTaskAttachmentDto"];
                        "application/json": components["schemas"]["ResponseOfListOfTaskAttachmentDto"];
                        "text/json": components["schemas"]["ResponseOfListOfTaskAttachmentDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: string;
                    projectId: string;
                    taskId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        ContentType?: string;
                        ContentDisposition?: string;
                        Headers?: {
                            [key: string]: string[];
                        };
                        /** Format: int64 */
                        Length?: number | string;
                        Name?: string;
                        FileName?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseOfTaskAttachmentDto"];
                        "application/json": components["schemas"]["ResponseOfTaskAttachmentDto"];
                        "text/json": components["schemas"]["ResponseOfTaskAttachmentDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/projects/{projectId}/Tasks/{taskId}/attachments/{attachmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: string;
                    projectId: string;
                    taskId: string;
                    attachmentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseOfTaskAttachmentDto"];
                        "application/json": components["schemas"]["ResponseOfTaskAttachmentDto"];
                        "text/json": components["schemas"]["ResponseOfTaskAttachmentDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: string;
                    projectId: string;
                    taskId: string;
                    attachmentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Response"];
                        "application/json": components["schemas"]["Response"];
                        "text/json": components["schemas"]["Response"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/projects/{projectId}/Tasks/{taskId}/attachments/{attachmentId}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: string;
                    projectId: string;
                    taskId: string;
                    attachmentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/projects/{projectId}/Tasks/{taskId}/subtasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: string;
                    projectId: string;
                    taskId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseOfListOfSubtaskDto"];
                        "application/json": components["schemas"]["ResponseOfListOfSubtaskDto"];
                        "text/json": components["schemas"]["ResponseOfListOfSubtaskDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: string;
                    projectId: string;
                    taskId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SubtaskRequest"];
                    "text/json": components["schemas"]["SubtaskRequest"];
                    "application/*+json": components["schemas"]["SubtaskRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseOfSubtaskDto"];
                        "application/json": components["schemas"]["ResponseOfSubtaskDto"];
                        "text/json": components["schemas"]["ResponseOfSubtaskDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/projects/{projectId}/Tasks/{taskId}/subtasks/{subtaskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: string;
                    projectId: string;
                    taskId: string;
                    subtaskId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseOfSubtaskDto"];
                        "application/json": components["schemas"]["ResponseOfSubtaskDto"];
                        "text/json": components["schemas"]["ResponseOfSubtaskDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: string;
                    projectId: string;
                    taskId: string;
                    subtaskId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SubtaskRequest"];
                    "text/json": components["schemas"]["SubtaskRequest"];
                    "application/*+json": components["schemas"]["SubtaskRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseOfSubtaskDto"];
                        "application/json": components["schemas"]["ResponseOfSubtaskDto"];
                        "text/json": components["schemas"]["ResponseOfSubtaskDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: string;
                    projectId: string;
                    taskId: string;
                    subtaskId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Response"];
                        "application/json": components["schemas"]["Response"];
                        "text/json": components["schemas"]["Response"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/Users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseOfListOfUserDto"];
                        "application/json": components["schemas"]["ResponseOfListOfUserDto"];
                        "text/json": components["schemas"]["ResponseOfListOfUserDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserRequest"];
                    "text/json": components["schemas"]["UserRequest"];
                    "application/*+json": components["schemas"]["UserRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseOfUserDto"];
                        "application/json": components["schemas"]["ResponseOfUserDto"];
                        "text/json": components["schemas"]["ResponseOfUserDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspaceId}/Users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: string;
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseOfUserDto"];
                        "application/json": components["schemas"]["ResponseOfUserDto"];
                        "text/json": components["schemas"]["ResponseOfUserDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: string;
                    userId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserRequest"];
                    "text/json": components["schemas"]["UserRequest"];
                    "application/*+json": components["schemas"]["UserRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseOfUserDto"];
                        "application/json": components["schemas"]["ResponseOfUserDto"];
                        "text/json": components["schemas"]["ResponseOfUserDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: string;
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Response"];
                        "application/json": components["schemas"]["Response"];
                        "text/json": components["schemas"]["Response"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseOfListOfWorkspaceDto"];
                        "application/json": components["schemas"]["ResponseOfListOfWorkspaceDto"];
                        "text/json": components["schemas"]["ResponseOfListOfWorkspaceDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WorkspaceRequest"];
                    "text/json": components["schemas"]["WorkspaceRequest"];
                    "application/*+json": components["schemas"]["WorkspaceRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseOfWorkspaceDto"];
                        "application/json": components["schemas"]["ResponseOfWorkspaceDto"];
                        "text/json": components["schemas"]["ResponseOfWorkspaceDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Workspaces/{workspaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseOfWorkspaceDto"];
                        "application/json": components["schemas"]["ResponseOfWorkspaceDto"];
                        "text/json": components["schemas"]["ResponseOfWorkspaceDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WorkspaceRequest"];
                    "text/json": components["schemas"]["WorkspaceRequest"];
                    "application/*+json": components["schemas"]["WorkspaceRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseOfWorkspaceDto"];
                        "application/json": components["schemas"]["ResponseOfWorkspaceDto"];
                        "text/json": components["schemas"]["ResponseOfWorkspaceDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workspaceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Response"];
                        "application/json": components["schemas"]["Response"];
                        "text/json": components["schemas"]["Response"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {unknown} */
        EFavoriteEntityType: "Project" | null;
        /** @enum {unknown} */
        EPriority: "None" | "Low" | "Medium" | "High";
        /** @enum {unknown} */
        EProjectRole: "Member" | "Lead" | "Owner";
        /** @enum {unknown} */
        EProjectStatus: "Planning" | "Active" | "OnHold" | "Archived";
        /** @enum {unknown} */
        EWorkspaceRole: "Member" | "Manager" | "Admin" | "Owner";
        /** Format: binary */
        IFormFile: string;
        JsonElement: unknown;
        LoginRequest: {
            email: string;
            password: string;
            rememberMe: boolean;
        };
        MeDto: {
            /** Format: uuid */
            id: string;
            email: string;
            firstName: string;
            lastName: null | string;
            avatarUrl: null | string;
            currentWorkspace: null | components["schemas"]["WorkspaceDto"];
        };
        MeRequest: {
            firstName: string;
            lastName: null | string;
        };
        MoveSectionRequest: {
            /** Format: uuid */
            previousSectionId: null | string;
            /** Format: uuid */
            nextSectionId: null | string;
        };
        MoveTaskRequest: {
            /** Format: uuid */
            sectionId: string;
            /** Format: uuid */
            previousTaskId: null | string;
            /** Format: uuid */
            nextTaskId: null | string;
        };
        ProjectDto: {
            /** Format: uuid */
            id: string;
            name: string;
            description: null | string;
            status: components["schemas"]["EProjectStatus"];
            priority: components["schemas"]["EPriority"];
            role: components["schemas"]["EProjectRole"];
            isFavorite: boolean;
            /** Format: date-time */
            dueDate: null | string;
            team: null | components["schemas"]["ProjectMemberDto"][];
        };
        ProjectMemberDto: {
            /** Format: uuid */
            id: string;
            email: string;
            firstName: string;
            lastName: null | string;
            avatarUrl: null | string;
            role: components["schemas"]["EProjectRole"];
        };
        ProjectRequest: {
            name: string;
            description: null | string;
            status: components["schemas"]["EProjectStatus"];
            priority: components["schemas"]["EPriority"];
            isFavorite: boolean;
            /** Format: date-time */
            dueDate: null | string;
            leadIds: null | string[];
            memberIds: null | string[];
        };
        RegisterRequest: {
            email: string;
            password: string;
            firstName: string;
            lastName: null | string;
        };
        Response: {
            message: string;
        };
        ResponseOfListOfProjectDto: {
            data?: null | components["schemas"]["ProjectDto"][];
            message?: string;
        };
        ResponseOfListOfProjectMemberDto: {
            data?: null | components["schemas"]["ProjectMemberDto"][];
            message?: string;
        };
        ResponseOfListOfSectionDto: {
            data?: null | components["schemas"]["SectionDto"][];
            message?: string;
        };
        ResponseOfListOfSubtaskDto: {
            data?: null | components["schemas"]["SubtaskDto"][];
            message?: string;
        };
        ResponseOfListOfTaskAttachmentDto: {
            data?: null | components["schemas"]["TaskAttachmentDto"][];
            message?: string;
        };
        ResponseOfListOfTaskDto: {
            data?: null | components["schemas"]["TaskDto"][];
            message?: string;
        };
        ResponseOfListOfUserDto: {
            data?: null | components["schemas"]["UserDto"][];
            message?: string;
        };
        ResponseOfListOfWorkspaceDto: {
            data?: null | components["schemas"]["WorkspaceDto"][];
            message?: string;
        };
        ResponseOfMeDto: {
            data?: components["schemas"]["MeDto"];
            message?: string;
        };
        ResponseOfProjectDto: {
            data?: components["schemas"]["ProjectDto"];
            message?: string;
        };
        ResponseOfSectionDto: {
            data?: components["schemas"]["SectionDto"];
            message?: string;
        };
        ResponseOfstring: {
            data?: null | string;
            message?: string;
        };
        ResponseOfSubtaskDto: {
            data?: components["schemas"]["SubtaskDto"];
            message?: string;
        };
        ResponseOfTaskAttachmentDto: {
            data?: components["schemas"]["TaskAttachmentDto"];
            message?: string;
        };
        ResponseOfTaskDto: {
            data?: components["schemas"]["TaskDto"];
            message?: string;
        };
        ResponseOfUserDto: {
            data?: components["schemas"]["UserDto"];
            message?: string;
        };
        ResponseOfWorkspaceDto: {
            data?: components["schemas"]["WorkspaceDto"];
            message?: string;
        };
        SectionDto: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        SectionRequest: {
            name: string;
        };
        SubtaskDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            taskId: string;
            name: string;
        };
        SubtaskRequest: {
            name: string;
        };
        TaskAttachmentDto: {
            /** Format: uuid */
            id: string;
            fileName: string;
            contentType: string;
            /** Format: int64 */
            size: number | string;
            downloadUrl: string;
        };
        TaskDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            sectionId: string;
            name: string;
            description: null | components["schemas"]["JsonElement"];
            priority: components["schemas"]["EPriority"];
            /** Format: date-time */
            dueDate: null | string;
            /** Format: date-time */
            completedAt: null | string;
            /** Format: date-time */
            assignedAt: null | string;
            assignee: null | components["schemas"]["ProjectMemberDto"];
            subtasks: null | components["schemas"]["SubtaskDto"][];
            attachments: null | components["schemas"]["TaskAttachmentDto"][];
        };
        TaskRequest: {
            /** Format: uuid */
            sectionId: string;
            name: string;
            description: null | components["schemas"]["JsonElement"];
            priority: components["schemas"]["EPriority"];
            /** Format: date-time */
            dueDate: null | string;
            /** Format: uuid */
            assigneeId: null | string;
        };
        UserDto: {
            /** Format: uuid */
            id: string;
            email: string;
            firstName: string;
            lastName: null | string;
            avatarUrl: null | string;
            role: components["schemas"]["EWorkspaceRole"];
            /** Format: date-time */
            joinedAt: string;
        };
        UserRequest: {
            email: string;
            firstName: string;
            lastName: null | string;
            avatarUrl: null | string;
            role: components["schemas"]["EWorkspaceRole"];
        };
        WorkspaceDto: {
            /** Format: uuid */
            id: string;
            name: string;
            role: components["schemas"]["EWorkspaceRole"];
            isPersonal: boolean;
            /** Format: int32 */
            members: number | string;
        };
        WorkspaceRequest: {
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
