// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zEFavoriteEntityType = z.enum(['Project']);

export const zEPriority = z.enum([
    'None',
    'Low',
    'Medium',
    'High'
]);

export const zEProjectRole = z.enum([
    'Member',
    'Lead',
    'Owner'
]);

export const zEProjectStatus = z.enum([
    'Planning',
    'Active',
    'OnHold',
    'Archived'
]);

export const zEWorkspaceRole = z.enum([
    'Member',
    'Manager',
    'Admin',
    'Owner'
]);

export const zIFormFile = z.string();

export const zJsonElement = z.unknown();

export const zLoginRequest = z.object({
    email: z.string(),
    password: z.string(),
    rememberMe: z.boolean()
});

export const zMeRequest = z.object({
    firstName: z.string(),
    lastName: z.string().nullable()
});

export const zMoveSectionRequest = z.object({
    previousSectionId: z.uuid().nullable(),
    nextSectionId: z.uuid().nullable()
});

export const zMoveTaskRequest = z.object({
    sectionId: z.uuid(),
    previousTaskId: z.uuid().nullable(),
    nextTaskId: z.uuid().nullable()
});

export const zProjectMemberDto = z.object({
    id: z.uuid(),
    email: z.string(),
    firstName: z.string(),
    lastName: z.string().nullable(),
    avatarUrl: z.string().nullable(),
    role: zEProjectRole
});

export const zProjectDto = z.object({
    id: z.uuid(),
    name: z.string(),
    description: z.string().nullable(),
    status: zEProjectStatus,
    priority: zEPriority,
    role: zEProjectRole,
    isFavorite: z.boolean(),
    dueDate: z.iso.datetime().nullable(),
    team: z.array(zProjectMemberDto).nullable()
});

export const zProjectRequest = z.object({
    name: z.string(),
    description: z.string().nullable(),
    status: zEProjectStatus,
    priority: zEPriority,
    dueDate: z.iso.datetime().nullable(),
    leadIds: z.array(z.uuid()).nullable(),
    memberIds: z.array(z.uuid()).nullable()
});

export const zRegisterRequest = z.object({
    email: z.string(),
    password: z.string(),
    firstName: z.string(),
    lastName: z.string().nullable()
});

export const zResponse = z.object({
    message: z.string()
});

export const zResponseOfListOfProjectDto = z.object({
    data: z.array(zProjectDto).nullish(),
    message: z.string().optional()
});

export const zResponseOfListOfProjectMemberDto = z.object({
    data: z.array(zProjectMemberDto).nullish(),
    message: z.string().optional()
});

export const zResponseOfProjectDto = z.object({
    data: zProjectDto.optional(),
    message: z.string().optional()
});

export const zResponseOfstring = z.object({
    data: z.string().nullish(),
    message: z.string().optional()
});

export const zSectionDto = z.object({
    id: z.uuid(),
    name: z.string()
});

export const zResponseOfListOfSectionDto = z.object({
    data: z.array(zSectionDto).nullish(),
    message: z.string().optional()
});

export const zResponseOfSectionDto = z.object({
    data: zSectionDto.optional(),
    message: z.string().optional()
});

export const zSectionRequest = z.object({
    name: z.string()
});

export const zSubtaskDto = z.object({
    id: z.uuid(),
    taskId: z.uuid(),
    name: z.string()
});

export const zResponseOfListOfSubtaskDto = z.object({
    data: z.array(zSubtaskDto).nullish(),
    message: z.string().optional()
});

export const zResponseOfSubtaskDto = z.object({
    data: zSubtaskDto.optional(),
    message: z.string().optional()
});

export const zSubtaskRequest = z.object({
    name: z.string()
});

export const zTaskAttachmentDto = z.object({
    id: z.uuid(),
    fileName: z.string(),
    contentType: z.string(),
    size: z.union([
        z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
        z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
    ]),
    downloadUrl: z.string()
});

export const zResponseOfListOfTaskAttachmentDto = z.object({
    data: z.array(zTaskAttachmentDto).nullish(),
    message: z.string().optional()
});

export const zResponseOfTaskAttachmentDto = z.object({
    data: zTaskAttachmentDto.optional(),
    message: z.string().optional()
});

export const zTaskDto = z.object({
    id: z.uuid(),
    sectionId: z.uuid(),
    name: z.string(),
    description: zJsonElement.nullable(),
    priority: zEPriority,
    dueDate: z.iso.datetime().nullable(),
    completedAt: z.iso.datetime().nullable(),
    assignedAt: z.iso.datetime().nullable(),
    assignee: zProjectMemberDto.nullable(),
    subtasks: z.array(zSubtaskDto).nullable(),
    attachments: z.array(zTaskAttachmentDto).nullable()
});

export const zResponseOfListOfTaskDto = z.object({
    data: z.array(zTaskDto).nullish(),
    message: z.string().optional()
});

export const zResponseOfTaskDto = z.object({
    data: zTaskDto.optional(),
    message: z.string().optional()
});

export const zTaskRequest = z.object({
    sectionId: z.uuid(),
    name: z.string(),
    description: zJsonElement.nullable(),
    priority: zEPriority,
    dueDate: z.iso.datetime().nullable(),
    assigneeId: z.uuid().nullable()
});

export const zUserDto = z.object({
    id: z.uuid(),
    email: z.string(),
    firstName: z.string(),
    lastName: z.string().nullable(),
    avatarUrl: z.string().nullable(),
    role: zEWorkspaceRole,
    joinedAt: z.iso.datetime()
});

export const zResponseOfListOfUserDto = z.object({
    data: z.array(zUserDto).nullish(),
    message: z.string().optional()
});

export const zResponseOfUserDto = z.object({
    data: zUserDto.optional(),
    message: z.string().optional()
});

export const zUserRequest = z.object({
    email: z.string(),
    role: zEWorkspaceRole
});

export const zWorkspaceDto = z.object({
    id: z.uuid(),
    name: z.string(),
    role: zEWorkspaceRole,
    isPersonal: z.boolean(),
    memberCount: z.union([
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

export const zMeDto = z.object({
    id: z.uuid(),
    email: z.string(),
    firstName: z.string(),
    lastName: z.string().nullable(),
    avatarUrl: z.string().nullable(),
    currentWorkspace: zWorkspaceDto.nullable()
});

export const zResponseOfListOfWorkspaceDto = z.object({
    data: z.array(zWorkspaceDto).nullish(),
    message: z.string().optional()
});

export const zResponseOfMeDto = z.object({
    data: zMeDto.optional(),
    message: z.string().optional()
});

export const zResponseOfWorkspaceDto = z.object({
    data: zWorkspaceDto.optional(),
    message: z.string().optional()
});

export const zWorkspaceRequest = z.object({
    name: z.string()
});

export const zRegisterBody = zRegisterRequest;

/**
 * OK
 */
export const zRegisterResponse = zResponse;

export const zLoginBody = zLoginRequest;

/**
 * OK
 */
export const zLoginResponse = zResponseOfMeDto;

/**
 * OK
 */
export const zLogoutResponse = zResponse;

export const zSwitchPath = z.object({
    workspaceId: z.uuid()
});

/**
 * OK
 */
export const zSwitchResponse = zResponseOfMeDto;

/**
 * OK
 */
export const zGetMeResponse = zResponseOfMeDto;

export const zUpdateMeBody = zMeRequest;

/**
 * OK
 */
export const zUpdateMeResponse = zResponseOfMeDto;

export const zUploadAvatarBody = z.object({
    avatar: zIFormFile.optional()
});

/**
 * OK
 */
export const zUploadAvatarResponse = zResponseOfstring;

export const zDeleteFavoritePath = z.object({
    workspaceId: z.uuid(),
    entityId: z.uuid()
});

/**
 * OK
 */
export const zDeleteFavoriteResponse = zResponse;

export const zCreateFavoritePath = z.object({
    workspaceId: z.uuid(),
    entityId: z.uuid()
});

export const zCreateFavoriteQuery = z.object({
    entityType: zEFavoriteEntityType
});

/**
 * OK
 */
export const zCreateFavoriteResponse = zResponse;

export const zGetProjectsPath = z.object({
    workspaceId: z.uuid()
});

/**
 * OK
 */
export const zGetProjectsResponse = zResponseOfListOfProjectDto;

export const zCreateProjectBody = zProjectRequest;

export const zCreateProjectPath = z.object({
    workspaceId: z.uuid()
});

/**
 * OK
 */
export const zCreateProjectResponse = zResponseOfProjectDto;

export const zDeleteProjectPath = z.object({
    workspaceId: z.uuid(),
    projectId: z.uuid()
});

/**
 * OK
 */
export const zDeleteProjectResponse = zResponse;

export const zGetProjectPath = z.object({
    workspaceId: z.uuid(),
    projectId: z.uuid()
});

/**
 * OK
 */
export const zGetProjectResponse = zResponseOfProjectDto;

export const zUpdateProjectBody = zProjectRequest;

export const zUpdateProjectPath = z.object({
    workspaceId: z.uuid(),
    projectId: z.uuid()
});

/**
 * OK
 */
export const zUpdateProjectResponse = zResponseOfProjectDto;

export const zGetProjectMembersPath = z.object({
    workspaceId: z.uuid(),
    projectId: z.uuid()
});

/**
 * OK
 */
export const zGetProjectMembersResponse = zResponseOfListOfProjectMemberDto;

export const zGetSectionsPath = z.object({
    workspaceId: z.uuid(),
    projectId: z.uuid()
});

/**
 * OK
 */
export const zGetSectionsResponse = zResponseOfListOfSectionDto;

export const zCreateSectionBody = zSectionRequest;

export const zCreateSectionPath = z.object({
    workspaceId: z.uuid(),
    projectId: z.uuid()
});

/**
 * OK
 */
export const zCreateSectionResponse = zResponseOfSectionDto;

export const zDeleteSectionPath = z.object({
    workspaceId: z.uuid(),
    projectId: z.uuid(),
    sectionId: z.uuid()
});

export const zDeleteSectionQuery = z.object({
    moveTasksTo: z.uuid().optional(),
    deleteTasks: z.boolean().optional()
});

/**
 * OK
 */
export const zDeleteSectionResponse = zResponseOfSectionDto;

export const zGetSectionPath = z.object({
    workspaceId: z.uuid(),
    projectId: z.uuid(),
    sectionId: z.uuid()
});

/**
 * OK
 */
export const zGetSectionResponse = zResponseOfSectionDto;

export const zUpdateSectionBody = zSectionRequest;

export const zUpdateSectionPath = z.object({
    workspaceId: z.uuid(),
    projectId: z.uuid(),
    sectionId: z.uuid()
});

/**
 * OK
 */
export const zUpdateSectionResponse = zResponseOfSectionDto;

export const zMoveSectionBody = zMoveSectionRequest;

export const zMoveSectionPath = z.object({
    workspaceId: z.uuid(),
    projectId: z.uuid(),
    sectionId: z.uuid()
});

/**
 * OK
 */
export const zMoveSectionResponse = zResponse;

export const zGetSubtasksPath = z.object({
    workspaceId: z.uuid(),
    projectId: z.uuid(),
    taskId: z.uuid()
});

/**
 * OK
 */
export const zGetSubtasksResponse = zResponseOfListOfSubtaskDto;

export const zCreateSubtaskBody = zSubtaskRequest;

export const zCreateSubtaskPath = z.object({
    workspaceId: z.uuid(),
    projectId: z.uuid(),
    taskId: z.uuid()
});

/**
 * OK
 */
export const zCreateSubtaskResponse = zResponseOfSubtaskDto;

export const zDeleteSubtaskPath = z.object({
    workspaceId: z.uuid(),
    projectId: z.uuid(),
    taskId: z.uuid(),
    subtaskId: z.uuid()
});

/**
 * OK
 */
export const zDeleteSubtaskResponse = zResponse;

export const zGetSubtaskPath = z.object({
    workspaceId: z.uuid(),
    projectId: z.uuid(),
    taskId: z.uuid(),
    subtaskId: z.uuid()
});

/**
 * OK
 */
export const zGetSubtaskResponse = zResponseOfSubtaskDto;

export const zUpdateSubtaskBody = zSubtaskRequest;

export const zUpdateSubtaskPath = z.object({
    workspaceId: z.uuid(),
    projectId: z.uuid(),
    taskId: z.uuid(),
    subtaskId: z.uuid()
});

/**
 * OK
 */
export const zUpdateSubtaskResponse = zResponseOfSubtaskDto;

export const zGetTaskAttachmentsPath = z.object({
    workspaceId: z.uuid(),
    projectId: z.uuid(),
    taskId: z.uuid()
});

/**
 * OK
 */
export const zGetTaskAttachmentsResponse = zResponseOfListOfTaskAttachmentDto;

export const zUploadTaskAttachmentBody = z.object({
    ContentType: z.string().optional(),
    ContentDisposition: z.string().optional(),
    Headers: z.record(z.string(), z.array(z.string())).optional(),
    Length: z.union([
        z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
        z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
    ]).optional(),
    Name: z.string().optional(),
    FileName: z.string().optional()
});

export const zUploadTaskAttachmentPath = z.object({
    workspaceId: z.uuid(),
    projectId: z.uuid(),
    taskId: z.uuid()
});

/**
 * OK
 */
export const zUploadTaskAttachmentResponse = zResponseOfTaskAttachmentDto;

export const zDeleteTaskAttachmentPath = z.object({
    workspaceId: z.uuid(),
    projectId: z.uuid(),
    taskId: z.uuid(),
    attachmentId: z.uuid()
});

/**
 * OK
 */
export const zDeleteTaskAttachmentResponse = zResponse;

export const zGetTaskAttachmentPath = z.object({
    workspaceId: z.uuid(),
    projectId: z.uuid(),
    taskId: z.uuid(),
    attachmentId: z.uuid()
});

/**
 * OK
 */
export const zGetTaskAttachmentResponse = zResponseOfTaskAttachmentDto;

export const zDownloadTaskAttachmentPath = z.object({
    workspaceId: z.uuid(),
    projectId: z.uuid(),
    taskId: z.uuid(),
    attachmentId: z.uuid()
});

export const zGetTasksPath = z.object({
    workspaceId: z.uuid(),
    projectId: z.uuid()
});

/**
 * OK
 */
export const zGetTasksResponse = zResponseOfListOfTaskDto;

export const zCreateTaskBody = zTaskRequest;

export const zCreateTaskPath = z.object({
    workspaceId: z.uuid(),
    projectId: z.uuid()
});

/**
 * OK
 */
export const zCreateTaskResponse = zResponseOfTaskDto;

export const zDeleteTaskPath = z.object({
    workspaceId: z.uuid(),
    projectId: z.uuid(),
    taskId: z.uuid()
});

/**
 * OK
 */
export const zDeleteTaskResponse = zResponse;

export const zGetTaskPath = z.object({
    workspaceId: z.uuid(),
    projectId: z.uuid(),
    taskId: z.uuid()
});

/**
 * OK
 */
export const zGetTaskResponse = zResponseOfTaskDto;

export const zUpdateTaskBody = zTaskRequest;

export const zUpdateTaskPath = z.object({
    workspaceId: z.uuid(),
    projectId: z.uuid(),
    taskId: z.uuid()
});

/**
 * OK
 */
export const zUpdateTaskResponse = zResponseOfTaskDto;

export const zMoveTaskBody = zMoveTaskRequest;

export const zMoveTaskPath = z.object({
    workspaceId: z.uuid(),
    projectId: z.uuid(),
    taskId: z.uuid()
});

/**
 * OK
 */
export const zMoveTaskResponse = zResponse;

export const zGetUsersPath = z.object({
    workspaceId: z.uuid()
});

/**
 * OK
 */
export const zGetUsersResponse = zResponseOfListOfUserDto;

export const zCreateUserBody = zUserRequest;

export const zCreateUserPath = z.object({
    workspaceId: z.uuid()
});

/**
 * OK
 */
export const zCreateUserResponse = zResponseOfUserDto;

export const zDeleteUserPath = z.object({
    workspaceId: z.uuid(),
    userId: z.uuid()
});

/**
 * OK
 */
export const zDeleteUserResponse = zResponse;

export const zGetUserPath = z.object({
    workspaceId: z.uuid(),
    userId: z.uuid()
});

/**
 * OK
 */
export const zGetUserResponse = zResponseOfUserDto;

export const zUpdateUserBody = zUserRequest;

export const zUpdateUserPath = z.object({
    workspaceId: z.uuid(),
    userId: z.uuid()
});

/**
 * OK
 */
export const zUpdateUserResponse = zResponseOfUserDto;

/**
 * OK
 */
export const zGetWorkspacesResponse = zResponseOfListOfWorkspaceDto;

export const zCreateWorkspaceBody = zWorkspaceRequest;

/**
 * OK
 */
export const zCreateWorkspaceResponse = zResponseOfWorkspaceDto;

export const zDeleteWorkspacePath = z.object({
    workspaceId: z.uuid()
});

/**
 * OK
 */
export const zDeleteWorkspaceResponse = zResponse;

export const zGetWorkspacePath = z.object({
    workspaceId: z.uuid()
});

/**
 * OK
 */
export const zGetWorkspaceResponse = zResponseOfWorkspaceDto;

export const zUpdateWorkspaceBody = zWorkspaceRequest;

export const zUpdateWorkspacePath = z.object({
    workspaceId: z.uuid()
});

/**
 * OK
 */
export const zUpdateWorkspaceResponse = zResponseOfWorkspaceDto;
